Quest:
  # Меню для админа - приоритет высокий (Готово)
  # Меню для пользователя - приоритет высокий (Готово)
  # Ачивка для выполнения строки с номером - приоритет средний
  # Ачивка для выполнения столбца с номером - приоритет средний
  # Ачивка для выполнения заданий диагонально - приоритет низкий
  # Выбор заданий для отображения сбоку (плейсхолдеры) - приоритет низкий

  leather-armor: #Тег достижения
    line: 1 #Строка в таблице достижений, нужна для подсчёта доп.очков
    column: 1 #Столбец в таблице достижений, нужен для подсчёта доп.очков
    icon: LEATHER_CHESTPLATE #Иконка достижения
    points: 10 #Сколько очков будет выдано при выполнении достижения
    display-name: '&fКожанная броня' #Название достижения
    lore: #Описание достижения
      - ''
      - '&7Условия:'
      - '&b-> Собрать полный набор Кожанной брони'
      - '&7Награда:'
      - '&b+10'
      - ''
      - '&7Статус: %quest_status%' #%quest_status% - заменяет собой статус выполнения достижения
    text-done: 'Вы успешно выполнили достижение &b[Кожанная броня]&f!'
  iron-armor:
    line: 1
    column: 2
    icon: IRON_CHESTPLATE
    points: 20
    display-name: '&fЖелезная броня'
    lore:
      - ''
      - '&7Условия:'
      - '&b-> Собрать полный набор Железной брони'
      - '&7Награда:'
      - '&b+20'
      - ''
      - '&7Статус: %quest_status%'
    text-done: 'Вы успешно выполнили достижение &b[Железная броня]&f!'
  golden-armor:
    line: 1
    column: 3
    icon: GOLDEN_CHESTPLATE
    points: 30
    display-name: '&fЗолотая броня'
    lore:
      - ''
      - '&7Условия:'
      - '&b-> Собрать полный набор Золотой брони'
      - '&7Награда:'
      - '&b+30'
      - ''
      - '&7Статус: %quest_status%'
    text-done: 'Вы успешно выполнили достижение &b[Золотая броня]&f!'
  diamond-armor:
    line: 1
    column: 4
    icon: DIAMOND_CHESTPLATE
    points: 40
    display-name: '&fАлмазная броня'
    lore:
      - ''
      - '&7Условия:'
      - '&b-> Собрать полный набор Алмазной брони'
      - '&7Награда:'
      - '&b+40'
      - ''
      - '&7Статус: %quest_status%'
    text-done: 'Вы успешно выполнили достижение &b[Алмазная броня]&f!'
  netherite-armor:
    line: 1
    column: 5
    icon: NETHERITE_CHESTPLATE
    points: 50
    display-name: '&fНезеритовая броня'
    lore:
      - ''
      - '&7Условия:'
      - '&b-> Собрать полный набор Незеритовой брони'
      - '&7Награда:'
      - '&b+50'
      - ''
      - '&7Статус: %quest_status%'
    text-done: 'Вы успешно выполнили достижение &b[Незеритовая броня]&f!'
  line1-done:
    line: 1
    column: 0
    icon: PAPER
    points: 100
    display-name: '&eПервая линия!'
    lore:
      - ''
      - '&7Условия:'
      - '&b-> Выполнить все задания в первой строке'
      - '&7Награда:'
      - '&b+100'
      - ''
      - '&7Статус: %quest_status%'
    text-done: 'Вы успешно выполнили достижение &b[Первая линия]&f!'